name: Deploy to /var/www/html via Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get install sshpass -y

    - name: Deploy HTML to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          cd /var/www/html &&
          git pull origin main &&
          chown -R www-data:www-data /var/www/html
        "
