name: Deploy HTML Only

on:
  push:
    branches:
      - main  # or master, depending on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSHpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Only HTML to Server
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Delete only .html files on the server
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP << 'EOF'
            find /var/www/html -name "*.html" -type f -delete
          EOF

          # Copy only .html files to server
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no *.html root@$SERVER_IP:/var/www/html

          # Restart Apache (if needed)
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP << 'EOF'
            sudo systemctl restart apache2
          EOF
